// The three lessons built for the pilot. All organisations, people, figures and
// references in the supplied materials are fictional teaching material.
// Intentionally flawed answers were written by the course authors to teach
// checking; they were not generated by a model.

export const TEACHING_LABEL =
  'Teaching material: every organisation, person, figure and reference in this lesson is fictional. The flawed answer was written on purpose to teach checking.';

const suitability = {
  slug: 'choosing-suitable-tasks',
  type: 'suitability',
  module: 1,
  title: 'Choosing suitable tasks for AI',
  version: '0.1 (September 2026)',
  minutes: '60–75',
  competencies: ['tool_selection', 'responsible_use'],
  summary: 'Decide whether AI suits a task by checking four things: the rules, the information involved, whether you can check the result, and what AI adds.',
  intro: [
    'AI chat tools are good at drafting, rephrasing, brainstorming, explaining and transforming text you give them. They are unreliable as a source of facts, current information, citations and exact calculations unless you check the result. They also have no knowledge of your assignment rules or your obligations to other people.',
    'This lesson gives you four questions to ask before you start. They are a checklist, not a formula: the answer depends on the task.',
  ],
  checklist: [
    ['Rules', 'Do the assignment, course or workplace rules allow AI for this purpose? If they are unclear, ask before you start.'],
    ['Information', 'What would you have to share? Is any of it personal, confidential or someone else\'s work, and is the tool approved for it?'],
    ['Checking', 'Could you tell whether the output is right? How would you check it, and is that realistic?'],
    ['Value', 'Does AI add something here, or is another method (a formula, an official source, asking a person, doing it yourself) quicker or more reliable?'],
  ],
  workedExample: {
    title: 'Worked example: a thank-you note in Spanish',
    scenario: 'You want to translate a 150-word thank-you note to your exchange host family into Spanish. You read some Spanish but write it slowly. Your language course is not involved.',
    reasoning: [
      ['Rules', 'This is personal, not assessed coursework, so no course rule applies.'],
      ['Information', 'The note contains first names only and nothing sensitive. Acceptable for a general tool.'],
      ['Checking', 'You can read the translation and check that it says what you meant. For tone, you could ask a Spanish-speaking friend.'],
      ['Value', 'AI saves time on a short, low-stakes text.'],
    ],
    decision: 'Suitable with conditions: read the translation back yourself and fix anything that does not say what you meant.',
  },
  scenarios: [
    { key: 'S1', text: 'You need ten possible themes for a student society\'s charity quiz night.', expected: ['suitable'], keywords: ['low', 'stakes', 'brainstorm', 'idea', 'judge', 'choose', 'no personal', 'easy'], why: 'Low stakes, nothing sensitive to share, and you can judge the ideas yourself.' },
    { key: 'S2', text: 'For a research project you interviewed six local shop owners. The transcripts contain their names, and one participant shared something in confidence. You want a summary from a free public chatbot.', expected: ['not_suitable'], keywords: ['privacy', 'personal', 'confiden', 'consent', 'ethic', 'approved', 'anonym', 'de-identif', 'participant', 'names'], why: 'Participants\' personal and confidential information would go to an unapproved tool. Check your ethics approval; use an approved tool with de-identified text, or summarise by hand.', critical: true },
    { key: 'S3', text: 'Your reflective essay brief says "AI tools may not be used for this assignment." You want AI to improve the flow of one paragraph.', expected: ['not_suitable'], keywords: ['rule', 'prohibit', 'not allowed', 'not permitted', 'brief', 'assignment', 'policy', 'integrity', 'may not'], why: 'The assignment prohibits AI use. Improving flow is still use. Ask your lecturer if you think an exception applies.', critical: true },
    { key: 'S4', text: 'You need total revenue from a 40-row spreadsheet of sales for a group report.', expected: ['with_conditions'], keywords: ['formula', 'spreadsheet', 'sum', 'check', 'verify', 'calculat', 'recalculat'], why: 'A spreadsheet formula is the reliable method. AI can help you write or explain the formula, but the calculation should be done and checked in the spreadsheet.' },
    { key: 'S5', text: 'You need today\'s official central bank interest rate for a report.', expected: ['not_suitable', 'with_conditions'], keywords: ['official', 'source', 'current', 'website', 'up to date', 'date', 'bank'], why: 'Current official figures should come from the official source. A chat tool may be out of date and may state a figure confidently.' },
  ],
  independent: {
    key: 'S6',
    text: 'At your part-time job, your manager asks you to draft a polite reply to a customer complaint. The complaint email includes the customer\'s full name, home address and order details.',
    expected: ['with_conditions'],
    keywords: ['personal', 'remove', 'anonym', 'address', 'approved', 'policy', 'review', 'check', 'workplace', 'employer'],
    why: 'Drafting a reply is a good use, but only with personal details removed (or in a tool your employer approves) and with you reviewing the reply before it is sent.',
  },
  hints: [
    'Take the four questions in order. The first "no" you reach usually decides the answer.',
    'Look for personal or confidential information and for any rule in the scenario. Those override convenience.',
    '"Suitable with conditions" needs the condition stated: what would you check or change?',
  ],
  ownTaskPrompt: 'Choose a task from one of your current courses. Decide whether AI is suitable, suitable with conditions, or not suitable, and explain your reasoning in three to five sentences using the four questions.',
  exampleResponse: {
    decisions: {
      S1: 'Suitable. Low stakes, no personal information, and I will choose from the ideas myself.',
      S2: 'Not suitable as described. The transcripts contain names and a confidential comment, and a free public chatbot is not approved for research data. I would check my ethics approval and either de-identify the text for an approved tool or summarise by hand.',
      S3: 'Not suitable. The brief says AI may not be used, and improving flow is still using it. I would ask the lecturer if I was unsure.',
      S4: 'Suitable with conditions. I would calculate the total with a SUM formula in the spreadsheet. AI could help me write the formula, and I would check it against a manual total of a few rows.',
      S5: 'Not suitable. I would take the rate from the central bank\'s website and note the date I checked it.',
      S6: 'Suitable with conditions, if I remove the name, address and order number, or use a tool my employer approves, and read the draft carefully before my manager sends it.',
    },
    own: 'Task: preparing a two-minute summary of a journal article for a seminar. Decision: suitable with conditions. Our module guide allows AI for "understanding readings" as long as it is disclosed. The article is published, so there is no confidential information. I can check a summary against the article, and I will quote only what I have checked. It saves time on the first pass, but I will write the final summary myself.',
  },
  commonMistakes: [
    'Treating "the tool is available" as permission. Rules come first.',
    'Choosing "suitable with conditions" without saying what the condition is.',
    'Forgetting that pasted text leaves your control: personal data about other people is the most common problem.',
    'Using AI for current facts or exact figures that an official source or a formula would give directly.',
  ],
  accessibility: 'All scenarios are text. Decisions use standard radio buttons and text fields that work with keyboard and screen readers, and nothing is timed. An educator can run the same six scenarios as a spoken discussion and record decisions for the student. Speech input, where enabled, does not affect assessment.',
  instructorNotes: [
    'Ask students to share an own-course task in pairs before submitting. Their tasks show you which rules in your course are unclear to them.',
    'Scenarios S2 and S3 are the most consequential; the automated feedback prioritises them.',
    'S5 accepts "not suitable" or "suitable with conditions" as long as the student points to the official source.',
    'Expected misconception: "AI is fine if I edit the output afterwards." Discuss S3: editing does not change whether use was permitted.',
  ],
};

const brief = {
  slug: 'defining-a-useful-request',
  type: 'brief',
  module: 2,
  title: 'Defining a useful request',
  version: '0.1 (September 2026)',
  minutes: '75–90',
  competencies: ['task_definition', 'instruction_quality', 'revision'],
  summary: 'Turn a vague request into a brief, write an instruction from it, check the output against your own success criteria, then change one thing and judge whether it helped.',
  intro: [
    'Most weak AI output starts with a request that leaves the model to guess the purpose, the reader, the materials and the limits. A brief makes those decisions explicit. It also gives you criteria to judge the output by.',
    'There is no single correct prompt or special phrase. Use the brief as a checklist, then include what this task needs.',
  ],
  briefFields: [
    ['objective', 'Objective', 'What should the finished work achieve? One or two sentences.'],
    ['audience', 'Audience', 'Who will read or use it, and what do they already know?'],
    ['inputs', 'Inputs and context', 'Which supplied materials or facts should the model use? Include only what you are allowed to share.'],
    ['constraints', 'Constraints', 'Length, tone, time, things to avoid, rules that apply.'],
    ['output_format', 'Output format', 'What shape should the answer take?'],
    ['success_criteria', 'Success criteria', 'Two to four checks someone else could apply to the result. One per line.'],
  ],
  workedExample: {
    title: 'Worked example: "help me study for my statistics exam"',
    before: 'Help me study for my stats exam.',
    brief: [
      ['Objective', 'Practise the two topics I got wrong in the mock exam: choosing between a t-test and a chi-square test, and interpreting p-values.'],
      ['Audience', 'Me: first-year business student, comfortable with averages, shaky on hypothesis tests.'],
      ['Inputs', 'The two mock exam questions I got wrong (pasted, no personal information).'],
      ['Constraints', 'Do not give answers until I have attempted each question. Use business examples.'],
      ['Output format', 'Five practice questions, one at a time.'],
      ['Success criteria', 'Each question needs a choice between the two tests.\nAnswers are explained in two or three sentences.\nI can check each explanation against my lecture notes.'],
    ],
    after: 'I\'m a first-year business student preparing for a statistics exam. In my mock exam I got these two questions wrong: [questions pasted]. Please give me five practice questions, one at a time, each asking me to choose between a t-test and a chi-square test or to interpret a p-value, using business examples. Wait for my answer before explaining, and keep each explanation to two or three sentences.',
    why: 'The revised request states the purpose, gives the model the relevant inputs, sets a constraint that protects the learning goal, and produces output the student can check against lecture notes.',
  },
  scenario: {
    title: 'Your task',
    text: 'Your Introduction to Marketing tutor has set a vague exercise: "Write something about how small businesses can use social media." You decide to make it useful by writing a 300-word briefing for a real-seeming client: the owner of Crumb & Co, a small bakery described in the source pack. Plan your request before you use AI.',
  },
  materials: [
    { id: 'P1', title: 'Source P1: Crumb & Co business profile (fictional)', body: 'Crumb & Co is an independent bakery in the fictional town of Harbourview, run by its owner, Sam, with two part-time staff. It sells bread, pastries and celebration cakes. Most weekday customers are regulars who live or work nearby. Celebration cakes are the most profitable product and are ordered 1–3 weeks in advance. Sam has an inactive Facebook page (last post 14 months ago) and no other social media accounts.' },
    { id: 'P2', title: 'Source P2: Owner\'s notes (fictional)', body: '"I can give this about three hours a week, no more. I don\'t want to pay for ads yet. I\'m not comfortable filming myself. Most cake orders come from word of mouth and people seeing cakes in the window. I want more cake orders, not more foot traffic — we\'re already busy on Saturday mornings."' },
    { id: 'P3', title: 'Source P3: Tutor\'s marking guidance (fictional)', body: 'Recommendations must be specific to the client, realistic for the client\'s resources, and justified with reference to the client information. Generic lists of "tips" will receive low marks. Maximum 300 words.' },
  ],
  hints: [
    'Re-read P2. Which three facts would change the recommendation completely if the model did not know them?',
    'A success criterion should be something you could tick or cross. "Good" is not checkable; "fits within three hours a week" is.',
    'When you revise, change one thing so you can tell what made the difference.',
  ],
  modelSystemPrompt: 'You are assisting a university student on a teaching exercise. Follow the student\'s instructions. Use only the information the student provides about the business; if something is not provided, say so rather than inventing it.',
  exampleResponse: {
    objective: 'Recommend one or two social media activities that could increase celebration cake orders for Crumb & Co, and justify them from the client information.',
    audience: 'Sam, the bakery owner. Knows the business well; not a marketer; has little time.',
    inputs: 'Business profile (P1) and owner\'s notes (P2), pasted. No personal information beyond the owner\'s first name, which is fictional.',
    constraints: '300 words maximum. Must fit within about three hours a week, no paid ads, no filming the owner. Aim at cake orders, not general foot traffic.',
    output_format: 'Short briefing: one-sentence recommendation, two or three reasons tied to the notes, a weekly routine, and one way to tell whether it is working.',
    success_criteria: 'Every recommended activity fits within three hours a week and needs no paid ads or filming the owner.\nEach reason refers to a fact from P1 or P2.\nIncludes one measure Sam could track (for example, orders that mention social media).\n300 words or fewer.',
    prompt_v1: 'I\'m writing a 300-word briefing for Sam, owner of a small bakery, on using social media to get more celebration cake orders. Here is the business profile and Sam\'s notes: [P1 and P2 pasted]. Recommend one or two specific activities that fit three hours a week, with no paid ads and no filming Sam. Give a one-sentence recommendation, reasons that refer to the notes, a weekly routine, and one thing Sam could measure. Don\'t add facts about the bakery that aren\'t in the notes.',
    assessment_v1: 'Met: word limit, no ads, reasons refer to notes. Partly met: the routine suggested daily posting, which is probably more than three hours a week once photos are taken. Not met: no measure suggested.',
    change_made: 'I added "Estimate the weekly time for each activity and keep the total under three hours," because the time limit was the criterion that failed.',
    prompt_v2: '[v1 prompt] + Estimate the weekly time for each activity and keep the total under three hours. Include exactly one measure Sam can track without new software.',
    assessment_v2: 'All four criteria met. The routine is now two posts a week of finished cakes from the window display, plus replies to messages, with a time estimate for each.',
    did_it_help: 'Yes, for the time criterion: the routine is now within three hours and the time estimates let me check that. It is one output, so I can\'t claim the new wording always works; the next check would be to run it again and see whether the estimates stay under three hours.',
  },
  commonMistakes: [
    'Writing a long, template-style prompt that still leaves out the client\'s constraints.',
    'Success criteria that can\'t be checked, such as "high quality" or "engaging".',
    'Changing several things at once, so it is impossible to tell what helped.',
    'Claiming a revision "worked" from a single output without saying which criterion improved.',
  ],
  accessibility: 'The brief is a set of labelled text fields, so it can be completed with a keyboard, a screen reader or speech input (where enabled). Students can submit without the live AI step if the provider is unavailable or AI is not permitted: they can record output from an approved tool, or evaluate the supplied example output instead. Nothing is timed.',
  instructorNotes: [
    'The central point is that the brief gives the student criteria to evaluate against. Watch for criteria that are not checkable.',
    'If AI use is prohibited for this assignment, students still complete the brief and prompt; the run button is disabled and the evaluation uses the example output.',
    'When comparing two prompts, hold the materials and model constant and remind students that one good output does not show a prompt is reliably better. The platform records the model identifier for each run.',
    'Expected misconception: "a longer prompt is a better prompt." The rubric deliberately does not reward length.',
  ],
};

const evidence = {
  slug: 'checking-claims-and-sources',
  type: 'evidence',
  module: 4,
  title: 'Checking claims and sources',
  version: '0.1 (September 2026)',
  minutes: '60–90',
  competencies: ['verification', 'revision', 'responsible_use'],
  summary: 'Check an AI-written answer against supplied sources, find the fabricated reference and the unsupported claims, correct the answer and say what is still uncertain.',
  intro: [
    'AI-written answers can contain references that do not exist, numbers that differ from the source, confident generalisations from weak evidence, and important omissions. They can read fluently while doing all of this.',
    'Checking means comparing each consequential claim with a source you can see, recording where you found the evidence, and removing or correcting what does not hold up.',
  ],
  verdicts: [
    ['supported', 'Supported by a source'],
    ['partly_supported', 'Partly supported or overstated'],
    ['contradicted', 'Contradicted by a source'],
    ['not_in_sources', 'Not found in the sources'],
    ['citation_unverifiable', 'Reference could not be verified'],
  ],
  workedExample: {
    title: 'Worked example: one claim, checked',
    claim: '"The library\'s busiest day is Saturday, with more than 600 visits on average."',
    steps: [
      'Find the number in the sources. Source A says Saturday averages 610 visits, against a weekday average of 360.',
      'Compare the wording. "More than 600" matches 610. "Busiest day" matches.',
      'Check the group and period. Both refer to 2025 library visits.',
      'Record it: Supported. Source A, paragraph 3: "Saturday is the busiest day, averaging 610 visits."',
    ],
  },
  brief: 'A member of the (fictional) Harbourview Town Council community committee asked an AI assistant: "Should Harbourview Library open on Sundays? Give a short answer with evidence." The answer below is about to be forwarded to the committee. Before anyone relies on it, check each claim against Sources A–C, correct the answer, and state what remains uncertain.',
  materials: [
    { id: 'A', title: 'Source A: Harbourview Library Annual Report 2025, excerpt (fictional)', body: 'The library is open Monday to Friday 09:00–18:00 and Saturday 10:00–16:00.\n\nTotal visits in 2025 were 118,400, down from 121,900 in 2024.\n\nSaturday is the busiest day, averaging 610 visits, compared with a weekday average of 360.\n\nFrom March to May 2025 the library trialled Sunday opening (12:00–16:00) on eight Sundays. Sunday attendance averaged 290 visits. Of 118 Sunday visitors surveyed at the door, 41 said they had not visited the library in the past year.\n\nNew memberships during the trial months were 6% higher than in the same months of 2024. Other factors, including a school reading campaign in April, may have contributed.' },
    { id: 'B', title: 'Source B: Town Council resident survey summary, November 2025 (fictional)', body: 'The survey received 1,020 responses online. Respondents chose to take part, so the results are not a random sample of residents.\n\n61% of respondents supported Sunday opening, 22% opposed it and 17% had no view.\n\nAmong supporters, the most popular hours were 12:00–16:00. 38% of supporters said they would visit on Sundays at least once a month.' },
    { id: 'C', title: 'Source C: Council budget note, January 2026 (fictional)', body: 'Opening 12:00–16:00 every Sunday would cost an estimated £74,000 a year, mainly premium-rate staffing, security and heating.\n\nThe cost would have to be met by reducing Saturday hours, reducing the libraries\' book budget, or new funding. No decision has been made.\n\nUnder current contracts Sunday shifts are voluntary. The staff union has been consulted but has not agreed to a Sunday rota.' },
  ],
  aiAnswerIntro: 'AI-style answer (intentionally flawed teaching material)',
  claims: [
    { key: 'C1', text: 'During the 2025 Sunday trial, attendance averaged 290 visits per Sunday, and about a third of surveyed Sunday visitors had not used the library in the previous year.', expected: ['supported'], source: 'A', explain: 'Source A gives 290 visits and 41 of 118 visitors (35%), which is about a third.' },
    { key: 'C2', text: 'The trial caused a 16% rise in new memberships.', expected: ['contradicted'], source: 'A', explain: 'Source A reports 6%, not 16%, and says other factors may have contributed, so the trial cannot be said to have caused it.' },
    { key: 'C3', text: 'Residents overwhelmingly back the change: nearly two-thirds of residents support Sunday opening.', expected: ['partly_supported'], near: ['contradicted'], source: 'B', explain: '61% of 1,020 self-selected online respondents supported it. That is not "residents" in general, and "overwhelmingly" overstates it.' },
    { key: 'C4', text: 'Sunday opening mainly attracts families with young children who cannot visit during the week.', expected: ['not_in_sources'], source: '', explain: 'None of the sources says who the Sunday visitors were. The claim is plausible, but it is unsupported.' },
    { key: 'C5', text: 'Research shows that extending weekend hours typically increases library use by around 20% (Marlow & Achebe, 2021, Journal of Public Library Management).', expected: ['citation_unverifiable'], near: ['not_in_sources'], source: '', explain: 'The reference is not among the sources and was invented for this exercise. A reference you cannot find must not be used, and the 20% figure goes with it.', critical: true },
    { key: 'C6', text: 'Sunday opening could be introduced at minimal cost by using existing staff.', expected: ['contradicted'], source: 'C', explain: 'Source C estimates £74,000 a year, says Sunday shifts are voluntary and says the union has not agreed.', critical: true },
  ],
  aiAnswerOpening: 'Yes. Harbourview Library should open on Sundays.',
  independent: {
    key: 'C7',
    text: '"Saturday is the library\'s quietest day, which is why Sunday opening is needed."',
    expected: ['contradicted'],
    explain: 'Source A says Saturday is the busiest day (610 visits against a weekday average of 360).',
  },
  hints: [
    'For each number, find the same number in a source. Does it match exactly, and does it describe the same group of people?',
    'For each reference, ask: is it one of the supplied sources? If not, could you find it in a library database? If you can\'t, don\'t use it.',
    'Check what the answer leaves out. Is there a source about costs or staffing that the answer ignores?',
  ],
  modelSystemPrompt: 'You are assisting a university student on a teaching exercise about verifying claims. Use only the sources the student provides. Do not add references or figures that are not in those sources. If the sources do not answer something, say so.',
  exampleCorrected: 'The evidence supports considering Sunday opening but does not settle the decision. In an eight-week trial in 2025 (12:00–16:00), Sundays averaged 290 visits, against about 360 on an average weekday and 610 on Saturdays, and 41 of 118 Sunday visitors surveyed (about a third) had not used the library in the previous year (Source A). New memberships during the trial months were 6% higher than a year earlier, but the library notes that a school reading campaign may have contributed (Source A). In a self-selected online survey of 1,020 residents, 61% supported Sunday opening and 22% opposed it (Source B). Opening every Sunday would cost an estimated £74,000 a year, to be met by cutting Saturday hours, reducing the book budget or finding new funding; Sunday shifts are voluntary and the staff union has not agreed a rota (Source C). I removed a claimed 20% increase attributed to a study I could not find, and a claim about families that no source supports.',
  exampleUncertainty: 'Whether trial attendance would continue beyond eight weeks; whether survey respondents represent residents generally; how many Sunday visits would be new rather than moved from Saturday; whether enough staff would volunteer; and which funding option the council would choose.',
  commonMistakes: [
    'Accepting a reference because it looks academic. Format is not evidence that a source exists.',
    'Fixing the number in a claim but keeping the causal wording ("caused").',
    'Treating a self-selected survey as the view of all residents.',
    'Checking the claims that are there but not noticing what is missing, here the cost and staffing constraints.',
    'Keeping the original "Yes" when the evidence supports a decision with trade-offs, not a verdict.',
  ],
  accessibility: 'All sources are plain text with headings and numbered paragraphs, so screen-reader users can navigate by heading. Claims are already split into separate items, so no highlighting or dragging is needed. Every verdict is a labelled radio button and statuses are shown in words, not only colour. Nothing is timed. As an alternative, the educator can run the verification orally using the same claim table.',
  instructorNotes: [
    'C5 (the invented reference) and C6 (the missing cost) are the most consequential and are prioritised in automated feedback.',
    'C3 accepts "partly supported" as correct and treats "contradicted" as close. Discuss the difference between a wrong number and an over-generalisation.',
    'Students often ask whether they may search for the Marlow & Achebe reference. Yes: searching and failing to find it is the right behaviour. Confirm afterwards that it was invented for the exercise.',
    'If AI use is permitted, the optional AI step asks the model to rewrite the answer from the sources. Ask students to check the rewrite too. It is a second place where errors can appear.',
    'Expected misconception: "if the AI cites a source, it read the source." Use C5 to discuss why that inference fails.',
  ],
};

export const LESSONS = {
  [suitability.slug]: suitability,
  [brief.slug]: brief,
  [evidence.slug]: evidence,
};

export const SAMPLE_LESSON_SLUG = evidence.slug;
